### ISSUE TITLE
Add alternative search engines and translation services

### ISSUE THREAD

**Issue by Calinou** [KELiON/cerebro#50] opened 2017-01-29 00:05 UTC
It looks like only Google search and Yandex translate are available right now. It'd be nice to have DuckDuckGo search as an option, for example.

**Comment by KELiON** [comment] 2017-01-30 10:12
Duplicate of #32. @captainhook said that he will try to implement DuckDuckGo plugin, so you can ping or coordinate to help him

**Closed by KELiON** 2017-01-30 10:12 UTC

**Comment by BurningTreeC** [comment] 2017-02-05 10:14
how about the option to simply define your search engine by url?
