### ISSUE TITLE
v 0.2.26-1 not working on arch linux

### ISSUE THREAD

**Issue by harryio** [KELiON/cerebro#124] opened 2017-02-16 21:30 UTC
just installed it via aur package, running inside gnome doesn't put an icon in the tray; running from terminal says

`cat: /var/lib/dbus/machine-id: No such file or directory
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: cat /var/lib/dbus/machine-id
cat: /var/lib/dbus/machine-id: No such file or directory

    at checkExecSyncError (child_process.js:495:13)
    at execSync (child_process.js:535:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at c (/usr/lib/cerebro/resources/app.asar/main.js:830:7109)
    at Object.<anonymous> (/usr/lib/cerebro/resources/app.asar/main.js:804:100)
    at __webpack_require__ (/usr/lib/cerebro/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/usr/lib/cerebro/resources/app.asar/main.js:172:20)
    at __webpack_require__ (/usr/lib/cerebro/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/usr/lib/cerebro/resources/app.asar/main.js:52:22)
    at __webpack_require__ (/usr/lib/cerebro/resources/app.asar/main.js:21:30)`

Although cerebro processes are running otherwise..

**Comment by maximbaz** [comment] 2017-02-17 12:16
Hey @harryio, I maintain aur package at the moment. I would be interested to know if the problem is with the package build instructions, or the app itself. Could you try running the [AppImage version](https://github.com/KELiON/cerebro/releases/download/0.2.6/cerebro-0.2.6-x86_64.AppImage) and telling me if it works? Just download it, make file executable and run it. Also did you maybe have any errors / warnings during aur package build?

**Comment by harryio** [comment] 2017-02-17 13:08
@maximbaz same error with the AppImage version.

There were no errors/warnings during the package build.

**Comment by maximbaz** [comment] 2017-02-17 13:17
Oh, have a look: #41, #86

**Comment by harryio** [comment] 2017-02-17 13:21
released or to be released?

**Comment by maximbaz** [comment] 2017-02-17 13:23
@KELiON is your man to answer this question :slightly_smiling_face:

**Comment by maximbaz** [comment] 2017-02-17 13:24
@harryio in meanwhile you can try aur package `cerebro-git`, that way you will test the state of the latest code in `master`.

**Comment by KELiON** [comment] 2017-02-17 17:19
@harryio @maximbaz hm, this fix is already included in few latest versions. You can solve it

> by creating a sym link to the file that actually was located at /etc/machine-id instead of /var/lib/dbus/machine-id

but I'd like to check what happens. Do you have installed node.js and do you have an ability to debug it a bit?

**Comment by hughwilliams94** [comment] 2017-02-22 11:16
I have just used the AppImage on Arch, it didn't work until I symlinked the file as above. I tried the cerebro-git Aur package which threw an error about cerebro.desktop being missing from an src folder. When building from source I get  no errors but the `npm run dev` fails with this message in a popup:

A Javascript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at exports.default (createWindow.js:48:18)
    at App._electron.app.on (main.development.js:36:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

and this terminal error is thrown:

```
WARNING in ./~/cross-spawn/index.js
[0] Module not found: Error: Cannot resolve module 'spawn-sync' in /home/$USER/Programs/cerebro/node_modules/cross-spawn
[0]  @ ./~/cross-spawn/index.js 32:26-47
[0] webpack: bundle is now VALID.

```

**Comment by harryio** [comment] 2017-02-22 11:38
@KELiON creating the symlink sure caused the error to disappear, but cerebro prompt is still unresponsive to clicks/typing. 
I have node installed, can debug.

**Comment by maximbaz** [comment] 2017-02-22 15:23
Also see #127, you may not be able to build the debug version at the moment.

**Comment by tunnckoCore** [comment] 2017-02-22 22:56
I'm on ArchLinux too and trying to get AppImage working, but the same error occures. I don't I have node globally, hence hate that - i have nvm. But if I remember correctly Atom installed it for me recently ;/ 

I don't see how we can debug using the appimage file.

```
~/Downloads  
% ❯ ./cerebro*.AppImage                                                                                 February 23, 00:43:42
/tmp/.mount_81VZp3/AppRun: line 77: 29955 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null
cat: /var/lib/dbus/machine-id: No such file or directory
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: cat /var/lib/dbus/machine-id
cat: /var/lib/dbus/machine-id: No such file or directory

    at checkExecSyncError (child_process.js:495:13)
    at execSync (child_process.js:535:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at c (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:830:7109)
    at Object.<anonymous> (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:804:100)
    at __webpack_require__ (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:172:20)
    at __webpack_require__ (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:52:22)
    at __webpack_require__ (/tmp/.mount_81VZp3/usr/bin/resources/app.asar/main.js:21:30)
```

**Comment by maximbaz** [comment] 2017-02-22 23:00
I don't think either that you can debug AppImage, you'd have to clone the repo and run a dev version, see section [Install](https://github.com/KELiON/cerebro#install) of the readme.

**Comment by KELiON** [comment] 2017-02-23 10:10
@tunnckoCore actually we don't need to debug it, I see that you have the issue with `node-machine-id`. Currently, you can fix it with symlink (#41).

**Comment by tunnckoCore** [comment] 2017-02-23 10:18
@KELiON actually, yea, i did that and it works. it is just amazing!

**Comment by mijoharas** [comment] 2017-02-26 18:24
I don't get any error messages, I just get the window showing up, and nothing happens when I type. The same happens when I go to preferences or plugins.

**Comment by mijoharas** [comment] 2017-02-26 18:31
sorry, ignore me, just realised that I have the issue described in https://github.com/KELiON/cerebro/issues/127 will try `cerebro-git`.

**Comment by m1aw** [comment] 2017-02-26 22:44
I just tried to install it directly from git and got:

`[0] yarn run v0.20.3
[1] yarn run v0.20.3
[0] $ node -r babel-register server.js 
[1] $ cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register ./app/main.development 
[0] Listening at http://localhost:3000
[1] cat: /var/lib/dbus/machine-id: No such file or directory
[1] App threw an error during load
[1] Error: Command failed: cat /var/lib/dbus/machine-id
[1] cat: /var/lib/dbus/machine-id: No such file or directory
[1] 
[1]     at checkExecSyncError (child_process.js:495:13)
[1]     at execSync (child_process.js:535:13)
[1]     at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
[1]     at c (/home/tuxcat/code/cerebro/node_modules/node-machine-id/dist/index.js:1:7164)
[1]     at Object.<anonymous> (/home/tuxcat/code/cerebro/app/lib/trackEvent.js:5:37)
[1]     at Module._compile (module.js:556:32)
[1]     at loader (/home/tuxcat/code/cerebro/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/tuxcat/code/cerebro/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12)
[1] A JavaScript error occurred in the main process
[1] Uncaught Exception:
[1] Error: Command failed: cat /var/lib/dbus/machine-id
[1] cat: /var/lib/dbus/machine-id: No such file or directory
[1] 
[1]     at checkExecSyncError (child_process.js:495:13)
[1]     at execSync (child_process.js:535:13)
[1]     at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
[1]     at c (/home/tuxcat/code/cerebro/node_modules/node-machine-id/dist/index.js:1:7164)
[1]     at Object.<anonymous> (/home/tuxcat/code/cerebro/app/lib/trackEvent.js:5:37)
[1]     at Module._compile (module.js:556:32)
[1]     at loader (/home/tuxcat/code/cerebro/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/tuxcat/code/cerebro/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12)
`

**Comment by maximbaz** [comment] 2017-02-26 23:21
Have you applied the workaround for `node-machine-id` mentioned 4 posts above?

**Comment by m1aw** [comment] 2017-02-26 23:35
Your are right @maximbaz. 
Sorry. Creating the symlink solves that issue, version from git is working now.

**Comment by tunnckoCore** [comment] 2017-02-27 00:25
Yea, symlinking works, but please ping us when there is more stable version, so we can update :)

**Comment by maximbaz** [comment] 2017-02-27 00:35
@KELiON do you want to follow up on this in https://github.com/automation-stack/node-machine-id/issues/8 ? 

By the way, to make it clear what is being tracked in this issue I suggest renaming it, or closing and reopening #41.

**Closed** 2017-03-13 15:20 UTC
