### ISSUE TITLE
On windows (10) the debug workflow doesn't work 

### ISSUE THREAD

**Issue by elis** [KELiON/cerebro#153] opened 2017-02-24 22:34 UTC
The linked directory somehow isn't updated with the changes in source director.

**Comment by KELiON** [comment] 2017-02-26 11:06
Can you try latest [cerebro-plugin](https://github.com/KELiON/cerebro-plugin), maybe [this PR](https://github.com/KELiON/cerebro-plugin/pull/7) fixes this problem

**Comment by KELiON** [comment] 2017-02-26 11:07
BTW, it is duplicate of #132

**Closed by KELiON** 2017-02-26 11:07 UTC

**Comment by elis** [comment] 2017-03-12 12:11
[This PR](https://github.com/KELiON/cerebro-plugin/pull/7) did not fix the issue for me, also updated to latest cerebro app.

**Comment by KELiON** [comment] 2017-03-13 09:25
@elis so, how do you deal with this issue? After each change in your plugin code you have to reload Cerebro? Or you have to rebuild your plugin each time to see the changes?

**Comment by elis** [comment] 2017-03-13 10:39
Alexander: I do both unfortunately, which slows development time
significantly. :(

-Eli
