### ISSUE TITLE
Recently used files or files on filesystem

### ISSUE THREAD

**Issue by pkajaba** [KELiON/cerebro#137] opened 2017-02-22 19:29 UTC
I would find really useful if there would be option to open files without writing down whole path.

For example there is picture `amazing_picture.png` inside of ~/Pictures. I enter `amazing_picture` and cerebro would show me a preview or give my possibility to open that picture with my preferred program.

**Comment by KELiON** [comment] 2017-02-23 09:17
Duplicate of #115

**Closed by KELiON** 2017-02-23 09:17 UTC
